export type Lesson = {
  id: string;
  number: number;
  module: string;
  title: string;
  level: "Foundation" | "Intermediate" | "Advanced" | "Production";
  duration: string;
  thesis: string;
  intuition: string;
  math: string[];
  algorithm: string[];
  implementation: string[];
  performance: string[];
  systems: string[];
  pitfalls: string[];
  exercises: { easy: string; medium: string; hard: string; debug: string; design: string };
};

export type Module = {
  id: string;
  title: string;
  subtitle: string;
  color: string;
};

export const modules: Module[] = [
  { id: "foundations", title: "I · Foundations", subtitle: "Vocabulary, semantics, and cost models", color: "cyan" },
  { id: "collectives", title: "II · The Collectives", subtitle: "Every operation, message by message", color: "violet" },
  { id: "algorithms", title: "III · Algorithms", subtitle: "Rings, trees, cubes, and hierarchies", color: "amber" },
  { id: "hardware", title: "IV · Hardware & Networks", subtitle: "From HBM to the switch fabric", color: "green" },
  { id: "libraries", title: "V · Production Libraries", subtitle: "Inside NCCL and its ecosystem", color: "pink" },
  { id: "training", title: "VI · AI Training", subtitle: "Parallelism and optimizer state", color: "blue" },
  { id: "inference", title: "VII · AI Inference", subtitle: "Serving, routing, and KV movement", color: "orange" },
  { id: "operations", title: "VIII · Reliability", subtitle: "Debug, profile, and design at scale", color: "red" },
];

const ex = (
  easy: string,
  medium: string,
  hard: string,
  debug: string,
  design: string,
) => ({ easy, medium, hard, debug, design });

export const lessons: Lesson[] = [
  {
    id: "why-collectives", number: 1, module: "foundations", title: "Why Collectives Exist", level: "Foundation", duration: "55 min",
    thesis: "A collective names a global data transformation; the runtime chooses a safe, topology-aware schedule that implements it.",
    intuition: "Four warehouses each know part of the inventory. Point-to-point messages are individual truck trips; a collective is the logistics plan that guarantees the right inventory appears in the right warehouses.",
    math: ["Running example: x₀=[1,2], x₁=[3,4], x₂=[5,6], x₃=[7,8].", "SUM(xᵢ)=[16,20].", "First-order message cost: T(n)=α+nβ, where α is startup latency and β is seconds per byte."],
    algorithm: ["State the ownership before and after communication.", "Separate semantics—what result is required—from schedule—who sends which chunk when.", "Map the logical schedule to physical links, then pipeline independent chunks."],
    implementation: ["Pure Python models ownership and transformation.", "Sockets make ordering and failure explicit.", "MPI/PyTorch expose group semantics.", "CUDA plus NCCL moves GPU-resident buffers without staging through application code."],
    performance: ["Count dependent rounds, not merely total sends.", "Find the busiest link and the slowest rank.", "Tiny messages are latency dominated; large messages are bandwidth dominated."],
    systems: ["Data-parallel gradients use allreduce.", "FSDP parameters use allgather and gradients use reduce-scatter.", "MoE tokens use all-to-all."],
    pitfalls: ["Treating allreduce as gather-to-rank-0 plus broadcast.", "Ignoring tensor shape and collective ordering.", "Quoting nominal link bandwidth without checking the actual route."],
    exercises: ex("Compute max-allreduce for the running example.", "Implement a central sum with four local workers.", "Prove that every output depends on every input.", "Make one rank enter a different collective and explain the hang.", "Design a collective API with explicit group, dtype, stream, and completion semantics."),
  },
  {
    id: "execution-model", number: 2, module: "foundations", title: "Ranks, Groups & Execution", level: "Foundation", duration: "60 min",
    thesis: "Collective correctness depends on matching membership, order, tensor metadata, and execution context across ranks.",
    intuition: "A rank is a seat number, a process is the person in the seat, and a communicator is the guest list. Everyone must follow the same agenda in the same order.",
    math: ["A communicator is an ordered set G={r₀…rₚ₋₁}.", "A collective instance is identified conceptually by (G, sequence number, operation, metadata).", "Completion is local: rank r returning does not imply every rank has returned."],
    algorithm: ["Bootstrap identities and endpoints.", "Create a consistent ordered group.", "Assign each collective an identical sequence position.", "Order GPU work with events or streams."],
    implementation: ["Contrast process-per-GPU and multi-GPU process models.", "Use torchrun environment variables for rank and world size.", "Show blocking CPU calls versus asynchronous GPU enqueue.", "Track work handles and stream dependencies."],
    performance: ["Late arrival appears as communication wait.", "Too many communicators increase setup and resource cost.", "Host synchronization can destroy compute/communication overlap."],
    systems: ["PyTorch process groups, MPI communicators, JAX device meshes, and NCCL communicators encode related concepts."],
    pitfalls: ["Confusing global rank with local GPU index.", "Reusing a buffer before asynchronous completion.", "Assuming host return means remote completion."],
    exercises: ex("Map eight ranks across two four-GPU hosts.", "Write a rank-to-device mapper.", "Model two overlapping communicators.", "Diagnose a rank-order mismatch.", "Design group creation for elastic membership."),
  },
  {
    id: "cost-model", number: 3, module: "foundations", title: "Latency, Bandwidth & Critical Paths", level: "Foundation", duration: "70 min",
    thesis: "Useful performance models count startup events, bytes on the critical path, reduction work, and contention on shared resources.",
    intuition: "Mailing one page has a fixed trip cost; adding pages adds carrying time. Ten parallel couriers help only if they do not share the same one-lane bridge.",
    math: ["Hockney: T=α+nβ.", "With reduction: T=kα+Vβ+nγ, where γ is reduction time per byte.", "Effective algorithm bandwidth=n/T; bus bandwidth normalizes for algorithmic traffic."],
    algorithm: ["Draw a time-expanded dependency graph.", "Mark parallel edges and shared physical resources.", "Sum only dependent stages, then apply contention ceilings."],
    implementation: ["Timestamp CPU phases and GPU events separately.", "Sweep powers-of-two message sizes.", "Fit α from the intercept and β from the large-message slope."],
    performance: ["P50 hides stragglers; record tail latency.", "Bidirectional bandwidth differs from one-way bandwidth.", "Memory copies may cap throughput before the link does."],
    systems: ["NCCL-tests reports time, algorithm bandwidth, and bus bandwidth.", "Nsight Systems exposes gaps between compute and communication."],
    pitfalls: ["Using Big-O alone.", "Adding parallel times serially.", "Treating advertised bandwidth as payload bandwidth."],
    exercises: ex("Evaluate α+nβ for 1 KiB and 1 GiB.", "Fit α and β from synthetic samples.", "Add a shared-link constraint.", "Explain a flat bandwidth curve at large sizes.", "Create a roofline for GPU-to-GPU communication."),
  },
  {
    id: "point-to-point", number: 4, module: "foundations", title: "Point-to-Point from TCP to RDMA", level: "Foundation", duration: "80 min",
    thesis: "Collectives are schedules of point-to-point transfers plus local computation, but transport semantics determine what schedules are legal and efficient.",
    intuition: "TCP is a managed phone call; RDMA is a pre-authorized loading dock where a remote machine can place goods directly into registered storage.",
    math: ["Throughput ≤ min(memory bandwidth, PCIe bandwidth, NIC bandwidth, path bottleneck).", "Bandwidth-delay product determines bytes required in flight.", "Serialization delay=message bits/link rate."],
    algorithm: ["Establish endpoints.", "Publish buffer addresses or receive slots.", "Post receives before sends when the transport requires it.", "Signal and observe completion."],
    implementation: ["Build framed TCP send/receive loops.", "Compare MPI_Send/MPI_Recv.", "Introduce registered memory, WQEs, QPs, CQs, and doorbells."],
    performance: ["Copies, syscalls, interrupts, registration, and queue depth matter.", "Zero-copy is a path property, not a slogan.", "Batching doorbells trades latency for throughput."],
    systems: ["NCCL transports include peer memory, shared memory, sockets, and network plugins.", "UCX selects among transports and memory types."],
    pitfalls: ["Assuming send completion means remote consumption.", "Posting circular blocking sends.", "Registering memory on every iteration."],
    exercises: ex("Frame a TCP message with a length header.", "Build ping-pong latency measurement.", "Compare eager and rendezvous protocols.", "Find a missing receive deadlock.", "Design buffer registration caching."),
  },
  {
    id: "semantic-contracts", number: 5, module: "foundations", title: "Collective Semantic Contracts", level: "Foundation", duration: "55 min",
    thesis: "Before optimizing, define root, counts, displacement, reduction operator, in-place legality, and final ownership precisely.",
    intuition: "A shipping manifest must say which boxes exist, who starts with them, who ends with them, and whether boxes are copied, combined, or exchanged.",
    math: ["Reduction requires an associative operator for safe regrouping.", "Commutativity permits rank reordering; associativity alone does not.", "Floating-point addition is not exactly associative."],
    algorithm: ["Write before/after ownership tables.", "Specify per-rank counts and data types.", "State ordering and aliasing constraints.", "Define error and completion behavior."],
    implementation: ["Model collectives as transformations over rank-indexed buffers.", "Use explicit recvcounts/displacements for variable collectives.", "Test in-place and zero-count edge cases."],
    performance: ["Noncommutative operators restrict schedules.", "Uneven counts create tail chunks and imbalance.", "In-place operation may reduce memory but constrain pipelining."],
    systems: ["MPI offers rich datatype and operator semantics; NCCL focuses on dense GPU tensors and common reductions."],
    pitfalls: ["Assuming bitwise reproducibility.", "Overlapping illegal input/output ranges.", "Using equal-count APIs for uneven shards."],
    exercises: ex("Specify gather ownership exactly.", "Test a noncommutative reduction.", "Explain floating-point result drift.", "Diagnose mismatched counts.", "Design a reproducible-sum mode."),
  },
  {
    id: "broadcast-barrier", number: 6, module: "collectives", title: "Broadcast & Barrier", level: "Foundation", duration: "65 min",
    thesis: "Broadcast distributes one root value; barrier distributes no payload but creates a group-wide ordering point.",
    intuition: "Broadcast copies a memo outward. Barrier is a starting gate that opens only after every runner arrives.",
    math: ["Linear broadcast critical depth P−1.", "Binomial-tree depth ⌈log₂P⌉.", "Barrier lower bound includes information flowing to and back from the group."],
    algorithm: ["Implement linear, binomial-tree, and pipelined-tree broadcast.", "Build dissemination or tree barrier.", "Trace the running value [1,2] from GPU0."],
    implementation: ["TCP root loop, then tree forwarding.", "MPI_Bcast and torch.distributed.broadcast.", "NCCL broadcast as GPU-enqueued work."],
    performance: ["Trees minimize rounds.", "Pipelining helps large payloads.", "Barrier time is dominated by the last arrival plus dissemination."],
    systems: ["Model initialization, seeds, metadata, and control flags use broadcast.", "Barriers should be rare in throughput-critical training."],
    pitfalls: ["Using barrier to fix unknown ordering bugs.", "Root mismatch.", "Timing a barrier without measuring arrival skew."],
    exercises: ex("Animate four-rank tree broadcast.", "Implement dissemination barrier.", "Pipeline a 1 GiB broadcast.", "Find a root mismatch.", "Choose a broadcast tree for asymmetric links."),
  },
  {
    id: "reduce", number: 7, module: "collectives", title: "Reduce & Reduction Operators", level: "Foundation", duration: "70 min",
    thesis: "Reduce combines corresponding elements under an operator and leaves the final result only at the root.",
    intuition: "Partial vote counts move up an election tree; intermediate offices combine them before the national total reaches headquarters.",
    math: ["y[j]=x₀[j]⊕x₁[j]⊕…⊕xₚ₋₁[j].", "Associativity permits tree regrouping.", "For SUM running example, y=[16,20]."],
    algorithm: ["Centralized reduction.", "Binary-tree reduction.", "Segmented pipelined reduction.", "Reduce into the root’s buffer safely."],
    implementation: ["Manual loops, NumPy axis reduction, PyTorch reduce, CUDA elementwise reduction, MPI custom operators."],
    performance: ["Reduction adds read-modify-write traffic.", "Tree root can receive only once per level.", "GPU reduction throughput can matter on very fast NVLink paths."],
    systems: ["Metrics aggregation and root-only decisions use reduce.", "Training usually needs allreduce or reduce-scatter instead."],
    pitfalls: ["Reading non-root output.", "Overflow or precision loss.", "Reordering noncommutative operations."],
    exercises: ex("Compute product and max reductions.", "Implement tree SUM.", "Add Kahan-style accumulation.", "Inject integer overflow.", "Design a user-defined reduction operator ABI."),
  },
  {
    id: "scatter-gather", number: 8, module: "collectives", title: "Scatter & Gather", level: "Foundation", duration: "60 min",
    thesis: "Scatter partitions root-owned data; gather assembles rank-owned shards at a root.",
    intuition: "A dealer distributes cards; later, one collector gathers one hand from every player in rank order.",
    math: ["Scatter maps root segment r to rank r.", "Gather output is concat(x₀,…,xₚ₋₁).", "Root storage grows with total element count."],
    algorithm: ["Direct root fan-out/fan-in.", "Tree forwarding with subranges.", "Variable-count scatterv/gatherv."],
    implementation: ["Track offsets and byte counts explicitly.", "Use MPI_Scatterv/Gatherv for uneven partitions.", "Avoid accidental host staging for GPU buffers."],
    performance: ["Root injection and memory bandwidth can bottleneck.", "Tree algorithms reduce root connection pressure.", "Uneven shard sizes extend the critical path."],
    systems: ["Dataset distribution, checkpoint assembly, and diagnostics use scatter/gather patterns."],
    pitfalls: ["Confusing element counts with byte counts.", "Incorrect displacement units.", "Assuming gather is a reduction."],
    exercises: ex("Scatter [1…8] over four ranks.", "Implement variable gather.", "Design a tree scatter.", "Find an offset bug.", "Gather a 2D tiled tensor."),
  },
  {
    id: "allgather", number: 9, module: "collectives", title: "Allgather", level: "Intermediate", duration: "70 min",
    thesis: "Allgather replicates every rank’s shard at every rank, trading communication and memory for complete local visibility.",
    intuition: "Each student owns one chapter and passes chapters around until everyone has the entire book.",
    math: ["yᵣ=concat(x₀,…,xₚ₋₁).", "Ring: P−1 steps, n/P bytes per step when n is final size.", "Per-rank received volume=(P−1)n/P."],
    algorithm: ["Naive gather+broadcast.", "Ring allgather.", "Recursive doubling for power-of-two ranks.", "Bruck-style exchange for short messages."],
    implementation: ["Forward the shard received in the prior ring step.", "Track owner index independently of physical sender.", "Support uneven allgatherv counts."],
    performance: ["Ring is bandwidth efficient.", "Recursive doubling uses fewer rounds but sends growing messages.", "Output memory is P times local shard size."],
    systems: ["FSDP parameter materialization, tensor metadata, and distributed embeddings use allgather."],
    pitfalls: ["Forwarding the local shard repeatedly.", "Wrong rank-order placement.", "Forgetting output-memory pressure."],
    exercises: ex("Trace four ring steps.", "Implement ring allgather over sockets.", "Compare Bruck and ring analytically.", "Corrupt one owner index.", "Choose an algorithm for 64-byte versus 1-GiB shards."),
  },
  {
    id: "reduce-scatter", number: 10, module: "collectives", title: "Reduce-Scatter", level: "Intermediate", duration: "75 min",
    thesis: "Reduce-scatter fuses global reduction with partitioned ownership, avoiding an unnecessary replicated result.",
    intuition: "Teams total every category, but each office keeps responsibility for only one final category.",
    math: ["First compute y=⊕ᵣxᵣ, then rank r receives shard y[r].", "Regular form requires reduced length divisible by P.", "Ring volume per rank=(P−1)n/P."],
    algorithm: ["Partition every vector into P chunks.", "At each ring step, receive one chunk, reduce it, and forward it.", "After P−1 steps each rank owns one fully reduced chunk."],
    implementation: ["Use ping-pong or protocol buffers.", "Fuse receive, reduction, and send.", "PyTorch reduce_scatter_tensor maps naturally to sharded gradients."],
    performance: ["Half of bandwidth-optimal ring allreduce.", "Saves replicated memory.", "Chunk imbalance and reduction throughput can limit scaling."],
    systems: ["FSDP and ZeRO shard gradients and optimizer ownership with reduce-scatter."],
    pitfalls: ["Confusing reduce-scatter with reduce followed by arbitrary scatter.", "Wrong chunk rotation.", "Non-divisible tensor sizes without padding."],
    exercises: ex("Pad a six-element tensor for four ranks.", "Trace chunk ownership.", "Fuse reduction into receive.", "Find an off-by-one rotation.", "Design uneven reduce-scatter."),
  },
  {
    id: "allreduce", number: 11, module: "collectives", title: "Allreduce", level: "Intermediate", duration: "90 min",
    thesis: "Bandwidth-optimal allreduce is reduce-scatter followed by allgather, while latency-oriented forms use trees or recursive exchange.",
    intuition: "First divide responsibility for producing final chapters; then circulate the finished chapters so everyone owns the book.",
    math: ["Ring T≈2(P−1)α+2(P−1)nβ/P+nγ.", "Recursive doubling uses log₂P rounds for suitable counts.", "Result on every rank: [16,20]."],
    algorithm: ["Naive central reduce+broadcast.", "Naive full-vector ring.", "Ring reduce-scatter+allgather.", "Tree and recursive-doubling variants."],
    implementation: ["Build socket ring first.", "Compare MPI_Allreduce and torch.distributed.all_reduce.", "Study NCCL chunk/slice/channel pipelining."],
    performance: ["Trees win latency-sensitive regions.", "Rings approach link bandwidth for large messages.", "Hierarchical allreduce respects fast intra-node and slower inter-node links."],
    systems: ["Synchronous data parallelism averages gradients with SUM plus scale.", "Small control reductions detect overflow or global termination."],
    pitfalls: ["Double-dividing gradients.", "Launching collectives in different parameter order.", "Assuming allreduce is bitwise deterministic."],
    exercises: ex("Compute average allreduce.", "Implement a full-vector ring.", "Derive ring traffic lower bound.", "Swap two collective calls on one rank.", "Build a size-based ring/tree selector."),
  },
  {
    id: "scan-neighbor", number: 12, module: "collectives", title: "Scan, Prefix & Neighbor Collectives", level: "Intermediate", duration: "65 min",
    thesis: "Prefix and neighborhood operations restrict which ranks influence each output, enabling algorithms different from global collectives.",
    intuition: "A running race checkpoint records everyone seen so far; a neighborhood exchange talks only to adjacent houses.",
    math: ["Inclusive scan yᵣ=⊕ᵢ₌₀ʳxᵢ.", "Running SUM outputs [1,2], [4,6], [9,12], [16,20].", "Neighbor complexity depends on graph degree, not total P."],
    algorithm: ["Linear prefix.", "Blelloch up-sweep/down-sweep.", "Recursive doubling scan.", "Graph-neighbor exchange."],
    implementation: ["Preserve operand order for noncommutative scans.", "Represent neighborhoods as graph communicators.", "Map halo regions into contiguous buffers."],
    performance: ["Parallel scan reaches logarithmic depth.", "Sparse neighborhoods reduce traffic.", "Packing noncontiguous halos may dominate."],
    systems: ["Prefix allocation, distributed offsets, graph analytics, and stencil halo exchange use these operations."],
    pitfalls: ["Mixing inclusive and exclusive scan.", "Breaking operand order.", "Ignoring pack/unpack overhead."],
    exercises: ex("Compute exclusive scan.", "Implement Blelloch scan.", "Handle non-power-of-two P.", "Find a reversed-operator bug.", "Design a 2D halo exchange."),
  },
  {
    id: "all-to-all", number: 13, module: "collectives", title: "All-to-All", level: "Intermediate", duration: "85 min",
    thesis: "All-to-all is personalized many-to-many exchange; it stresses injection, routing, receive placement, and congestion more than replication collectives.",
    intuition: "Every airport sends a different bag to every other airport at once. The challenge is not copying one item, but coordinating a complete traffic matrix.",
    math: ["Rank i sends chunk xᵢ⟶ⱼ to rank j.", "Each rank sends and receives approximately (P−1)n/P.", "Pairwise exchange takes P−1 rounds without additional path parallelism."],
    algorithm: ["Direct pairwise exchange.", "Staged/Bruck exchange.", "Topology-aware hierarchical all-to-all.", "Variable alltoallv for token imbalance."],
    implementation: ["Build destination-indexed send counts and offsets.", "Exchange counts before payloads.", "Pack tokens by expert, transfer, then unpermute."],
    performance: ["Many simultaneous flows create incast and path collisions.", "Small chunks are latency dominated.", "Load imbalance makes the largest receive count critical."],
    systems: ["MoE expert dispatch, distributed transpose, and FFTs use all-to-all."],
    pitfalls: ["Incorrect displacement arrays.", "Assuming equal expert load.", "Creating P² tiny messages without batching."],
    exercises: ex("Draw a four-rank traffic matrix.", "Implement pairwise all-to-all.", "Model Zipf expert load.", "Find a send/receive-count mismatch.", "Design hierarchical MoE dispatch."),
  },
  {
    id: "ring-pipeline", number: 14, module: "algorithms", title: "Ring & Pipeline Ring", level: "Intermediate", duration: "80 min",
    thesis: "Rings maximize steady-state link utilization by circulating chunks, but pay linear startup depth and depend on balanced logical edges.",
    intuition: "A bucket brigade keeps every person busy once the pipeline fills; the first and last buckets still pay fill and drain time.",
    math: ["Ring depth P−1 per phase.", "Chunk time≈α+cβ.", "Pipeline total≈fill+steady state+drain."],
    algorithm: ["Choose direction and neighbor mapping.", "Partition into owner-addressed chunks.", "Schedule chunk rotations.", "Add multiple channels or counter-rotating rings."],
    implementation: ["Maintain send/receive step indices.", "Use protocols that expose readiness per slice.", "Avoid overwriting chunks still in flight."],
    performance: ["Chunk size balances startup overhead and overlap.", "One slow edge limits the whole ring.", "Multiple rings help only with distinct physical capacity."],
    systems: ["NCCL constructs rings from discovered topology and uses them heavily for large collectives."],
    pitfalls: ["Drawing a logical ring without physical-path analysis.", "Too many tiny slices.", "Unsafe buffer reuse."],
    exercises: ex("Trace owner indices.", "Build a chunked ring simulator.", "Optimize chunk size analytically.", "Break one readiness signal.", "Construct two edge-disjoint rings."),
  },
  {
    id: "trees", number: 15, module: "algorithms", title: "Binary, Binomial & Double Trees", level: "Intermediate", duration: "80 min",
    thesis: "Trees reduce dependency depth; tree shape determines parent pressure, bidirectional use, and resilience to topology asymmetry.",
    intuition: "A phone tree spreads news exponentially; a second complementary tree can use links left idle by the first.",
    math: ["Balanced binary depth≈log₂P.", "Binomial tree doubles informed ranks each round.", "Two complementary trees split data to use both directions."],
    algorithm: ["Construct binary and binomial parent/child relations.", "Pipeline segments across levels.", "Build complementary double trees with opposite leaves/internal nodes."],
    implementation: ["Encode parent and children per channel.", "Handle non-power-of-two ranks.", "Synchronize segment readiness independently."],
    performance: ["Low latency for small and medium messages.", "Internal nodes may transmit and receive multiple times.", "Double trees improve aggregate link utilization."],
    systems: ["NCCL tree algorithms and double-binary-tree designs target low latency and scalable bandwidth."],
    pitfalls: ["Overloading one NIC-facing GPU.", "Assuming rank-number trees match topology.", "Serializing independent children."],
    exercises: ex("Build a binomial tree for six ranks.", "Pipeline four segments.", "Compare tree and ring crossover.", "Find a parent-cycle bug.", "Map double trees to a dual-rail fabric."),
  },
  {
    id: "recursive-exchange", number: 16, module: "algorithms", title: "Recursive Doubling, Halving & Butterfly", level: "Advanced", duration: "85 min",
    thesis: "Recursive exchange doubles the amount of known information each round, reaching logarithmic depth when rank counts and data partitions cooperate.",
    intuition: "In each round, partners who know disjoint halves exchange everything they know; knowledge doubles like a rumor spreading.",
    math: ["Partner at round k is rank XOR 2ᵏ.", "Rounds=log₂P for power-of-two P.", "Message sizes grow in doubling and shrink in halving."],
    algorithm: ["Recursive doubling allgather/allreduce.", "Recursive halving reduce-scatter.", "Butterfly exchange.", "Fold/unfold extra ranks for non-powers of two."],
    implementation: ["Compute partner with XOR.", "Track contiguous or indexed data regions.", "Special-case non-power-of-two ranks safely."],
    performance: ["Excellent startup depth.", "Large later-round messages may contend.", "Partner paths may traverse the same physical uplinks."],
    systems: ["MPI implementations commonly use recursive exchange in short-message regions."],
    pitfalls: ["Assuming P is a power of two.", "Overlapping wrong buffer halves.", "Ignoring topology distance of XOR partners."],
    exercises: ex("List partners for P=8.", "Implement recursive doubling.", "Extend to P=6.", "Find an incorrect fold mapping.", "Create topology-aware logical rank ordering."),
  },
  {
    id: "topologies", number: 17, module: "algorithms", title: "2D/3D Rings, Torus, Fat Tree & Dragonfly", level: "Advanced", duration: "90 min",
    thesis: "Topology-aware algorithms decompose communication along physical dimensions to reduce contention and expensive global traffic.",
    intuition: "Local streets, highways, and flights have different costs; good logistics consolidate locally before using scarce long-distance routes.",
    math: ["For P=a×b, a 2D algorithm decomposes row and column phases.", "Bisection bandwidth limits simultaneous cross-partition traffic.", "Oversubscription ratio compares downstream demand with uplink capacity."],
    algorithm: ["Dimension-ordered rings on meshes/torus.", "Local-group then global-group hierarchy.", "Rail-aware fat-tree mapping.", "Dragonfly group-local and global phases."],
    implementation: ["Discover topology and assign coordinates.", "Create subcommunicators by dimension.", "Select leaders or shards for global phases."],
    performance: ["Reduce expensive-link byte volume.", "Avoid synchronized hotspots.", "Adaptive routing can invalidate static contention assumptions."],
    systems: ["Large clusters combine intra-GPU, intra-node, rack, and fabric layers."],
    pitfalls: ["Equating logical topology with cabling.", "Ignoring oversubscription.", "Choosing leaders that share one PCIe or NIC bottleneck."],
    exercises: ex("Map 16 ranks to a 4×4 mesh.", "Build row/column groups.", "Model bisection traffic.", "Find a rail collision.", "Design an allreduce for four racks."),
  },
  {
    id: "algorithm-selection", number: 18, module: "algorithms", title: "Algorithm Selection & Autotuning", level: "Advanced", duration: "75 min",
    thesis: "Production selection is a constrained optimization over collective, size, ranks, topology, protocol, channels, and current contention.",
    intuition: "A route planner chooses walking, train, or plane based on trip length, departure overhead, congestion, and available connections.",
    math: ["Choose argminₐ T(a | n,P,topology,load).", "Piecewise models create size-dependent crossover points.", "Online tuning trades exploration cost against performance gain."],
    algorithm: ["Filter illegal algorithms.", "Estimate cost by protocol and topology.", "Use calibrated thresholds.", "Optionally benchmark and cache winners."],
    implementation: ["Build a decision table, then a model-driven selector.", "Record hardware identity and software version with tuning data.", "Provide deterministic overrides."],
    performance: ["Threshold hysteresis prevents unstable switching.", "Concurrent jobs shift effective bandwidth.", "Warm-up and graph capture alter launch cost."],
    systems: ["MPI/NCCL implementations use internal heuristics, environment overrides, and topology models."],
    pitfalls: ["Benchmarking only powers of two.", "Overfitting one idle machine.", "Using stale tuning after topology changes."],
    exercises: ex("Find a ring/tree crossover.", "Implement a selector.", "Add topology features.", "Diagnose a discontinuity.", "Design safe online autotuning."),
  },
  {
    id: "gpu-memory", number: 19, module: "hardware", title: "GPU Memory & Execution", level: "Advanced", duration: "90 min",
    thesis: "Collective kernels are constrained by HBM traffic, cache behavior, synchronization granularity, occupancy, and the memory visibility rules of the transport.",
    intuition: "HBM is a warehouse, L2 a loading area, shared memory a workbench, and registers the worker’s hands. Moving an item repeatedly can cost more than combining it.",
    math: ["Reduction arithmetic intensity is usually low.", "Effective throughput≤min(HBM read/write, link, protocol).", "Occupancy is constrained by registers, shared memory, blocks, and warps."],
    algorithm: ["Load source slices.", "Reduce vectorized elements.", "Store or forward results.", "Signal slice completion with appropriate ordering."],
    implementation: ["Use coalesced vector loads/stores.", "Distinguish device, system, and peer visibility.", "Use stream and event dependencies instead of global synchronization."],
    performance: ["Extra copies multiply HBM traffic.", "Too few blocks underutilize SMs; too many compete with training kernels.", "L2 residency can help repeated protocol metadata."],
    systems: ["NCCL kernels combine movement, reduction, and synchronization on CUDA streams."],
    pitfalls: ["Assuming network bandwidth is always the ceiling.", "Excessive __syncthreads().", "Ignoring alignment and tail elements."],
    exercises: ex("Count HBM bytes for vector SUM.", "Write a coalesced add kernel.", "Estimate occupancy.", "Find a missing memory fence.", "Design compute-friendly communication occupancy."),
  },
  {
    id: "pcie-numa", number: 20, module: "hardware", title: "PCIe, Switches & NUMA", level: "Advanced", duration: "80 min",
    thesis: "PCIe topology determines whether GPU traffic stays peer-to-peer, crosses a switch, traverses a root complex, or detours through host memory.",
    intuition: "Two rooms may be nearby on a floor plan yet require passing through a distant security checkpoint because of the building’s access topology.",
    math: ["Path throughput is capped by the narrowest negotiated link.", "Shared upstream links divide capacity among active children.", "NUMA distance adds CPU-memory and control-path penalties."],
    algorithm: ["Build a topology graph from sysfs and runtime queries.", "Classify peer-access paths.", "Place ranks and CPU threads near GPUs and NICs."],
    implementation: ["Inspect lspci trees, nvidia-smi topo, CPU affinity, and NUMA nodes.", "Enable peer access where legal.", "Pin proxy threads deliberately."],
    performance: ["PCIe payload efficiency depends on transaction sizes.", "ACS/IOMMU policies may change peer paths.", "A PCIe switch can be full duplex yet share upstream bandwidth."],
    systems: ["Topology-aware runtimes prefer NVLink or same-switch peers and align NICs with local GPUs."],
    pitfalls: ["Reading only PCI bus IDs.", "Assuming x16 means current maximum speed.", "Ignoring CPU affinity of progress threads."],
    exercises: ex("Draw a PCIe tree.", "Map ranks to nearest NICs.", "Calculate shared-uplink demand.", "Diagnose host-staged traffic.", "Design placement for dual-socket eight-GPU host."),
  },
  {
    id: "nvlink", number: 21, module: "hardware", title: "NVLink, NVSwitch & NVLink Switch", level: "Advanced", duration: "90 min",
    thesis: "NVLink fabrics provide high-bandwidth GPU memory connectivity, but generation, link multiplicity, routing, and switch domains still shape collective schedules.",
    intuition: "Direct NVLink edges are express lanes; NVSwitch is a high-capacity interchange that lets many GPU pairs communicate concurrently.",
    math: ["Aggregate GPU bandwidth is the sum of usable links subject to routing and endpoint limits.", "Bisection and per-port bandwidth bound simultaneous traffic.", "Full-duplex rates must not be compared with one-direction payload rates."],
    algorithm: ["Construct multiple rings across distinct links.", "Use trees that balance switch ports.", "Decompose across NVSwitch domains before network phases."],
    implementation: ["Query peer connectivity and link state.", "Use peer memory operations and CUDA transport primitives.", "Monitor link counters and errors."],
    performance: ["Topology may be near-uniform inside a switch domain.", "HBM or SM reduction can become the limiter.", "Inter-domain links reintroduce hierarchy."],
    systems: ["DGX/HGX platforms exploit NVSwitch for intra-node collectives; larger NVLink domains extend GPU fabric scale."],
    pitfalls: ["Using marketing aggregate bandwidth as per-flow throughput.", "Assuming every generation has identical semantics.", "Ignoring failed or degraded links."],
    exercises: ex("Draw an eight-GPU switch domain.", "Construct two rings.", "Model HBM-limited reduction.", "Identify a degraded-link signature.", "Design two-level NVLink+NIC allreduce."),
  },
  {
    id: "rdma", number: 22, module: "hardware", title: "InfiniBand, RoCE & GPUDirect RDMA", level: "Advanced", duration: "100 min",
    thesis: "RDMA lets NICs transfer registered GPU memory with low CPU involvement; correctness still relies on queue semantics, keys, ordering, and completion.",
    intuition: "After a loading dock verifies a warehouse address and access key, trucks can place goods directly without asking the front office for every box.",
    math: ["Bandwidth-delay product sets required in-flight bytes.", "Queue depth×message size must cover the BDP for full throughput.", "End-to-end latency includes GPU/NIC/PCIe/switch/remote components."],
    algorithm: ["Register memory and exchange keys.", "Create and transition QPs.", "Post WQEs and ring doorbells.", "Poll CQs or use event-driven completion."],
    implementation: ["Explain RC and UD semantics.", "Map scatter/gather entries to buffers.", "Use GPUDirect-capable paths and memory registration caches."],
    performance: ["Doorbell batching, inline data, MTU, queue depth, and CQ moderation matter.", "PCIe relaxed ordering and DMA engines affect throughput.", "CPU polling placement affects progress."],
    systems: ["NCCL network plugins translate collective steps into transport operations; UCX and verbs expose lower layers."],
    pitfalls: ["Invalid lkey/rkey.", "Confusing local WQE completion with application consumption.", "Assuming RoCE is lossless without fabric configuration."],
    exercises: ex("Label an RC QP exchange.", "Calculate BDP and queue depth.", "Compare read/write/send semantics.", "Diagnose an rkey failure.", "Design a registration cache."),
  },
  {
    id: "network-control", number: 23, module: "hardware", title: "Packets, Flow & Congestion Control", level: "Advanced", duration: "100 min",
    thesis: "Collective traffic is synchronized and bursty; routing, buffering, credits, ECN, and congestion control determine whether nominal bandwidth becomes useful throughput.",
    intuition: "Thousands of buses leaving stadiums simultaneously overwhelm intersections even when every road looked sufficient in isolation.",
    math: ["Queue growth rate=input rate−service rate.", "PFC pause propagates backpressure by priority.", "ECN marks before loss; controllers adjust sending rate from feedback."],
    algorithm: ["Credit-based flow control.", "PFC/ECN/DCQCN and rate adaptation.", "Adaptive routing, ECMP, spraying, and ordering-aware multipath."],
    implementation: ["Relate packets to collective chunks.", "Inspect switch port queues, marks, pauses, drops, and retransmissions.", "Correlate fabric counters with GPU timelines."],
    performance: ["Incast creates transient queue spikes.", "Hash collisions serialize otherwise independent flows.", "Packet spraying improves balance but complicates ordering."],
    systems: ["InfiniBand credit flow and adaptive routing differ from RoCE Ethernet designs; modern AI fabrics tune both endpoints and switches."],
    pitfalls: ["Treating zero packet loss as zero congestion.", "Enabling PFC without deadlock analysis.", "Looking only at average utilization."],
    exercises: ex("Calculate queue growth.", "Simulate four-flow incast.", "Compare ECMP and spraying.", "Diagnose pause storms.", "Design telemetry for collective congestion."),
  },
  {
    id: "offload", number: 24, module: "hardware", title: "SHARP, Switch Offload & DPUs", level: "Production", duration: "80 min",
    thesis: "In-network reduction moves parts of the collective’s arithmetic and aggregation into the fabric, reducing endpoint and cross-fabric traffic when operations fit hardware constraints.",
    intuition: "Instead of shipping every ballot to headquarters, regional sorting centers combine totals while ballots are already passing through.",
    math: ["A reduction tree can combine k inputs into one on each switch level.", "Cross-section bytes fall when partials are aggregated before scarce links.", "Offload benefit must exceed setup, resource, and fallback costs."],
    algorithm: ["Allocate aggregation contexts.", "Map groups and operators to switch capabilities.", "Reduce in-network and distribute results.", "Fallback for unsupported sizes/types."],
    implementation: ["Describe SHARP collectives, programmable pipelines, and DPU-assisted control/data movement.", "Manage limited switch resources and job isolation."],
    performance: ["Excellent for supported reductions and repeated groups.", "Setup and small-message behavior matter.", "Switch arithmetic and context capacity are finite."],
    systems: ["SHARP-enabled fabrics, BlueField DPUs, and transport offload complement rather than replace endpoint collectives."],
    pitfalls: ["Assuming arbitrary operators are offloadable.", "Ignoring multi-tenant context limits.", "Comparing offloaded and host paths with different routing."],
    exercises: ex("Draw an in-network reduction tree.", "Model bytes saved at the core.", "Choose fallback thresholds.", "Diagnose exhausted contexts.", "Design tenant-safe offload allocation."),
  },
  {
    id: "ecosystem", number: 25, module: "libraries", title: "MPI, Gloo, UCX, RCCL, oneCCL & XCCL", level: "Advanced", duration: "85 min",
    thesis: "Communication stacks differ in semantic breadth, accelerator focus, transport abstraction, integration model, and tuning philosophy.",
    intuition: "MPI is a full shipping standard, UCX a transport broker, and accelerator collective libraries specialized high-speed logistics operators.",
    math: ["Compare supported collectives, datatypes, memory locations, progress models, and transport costs.", "Layering adds abstraction value but may add setup or dispatch overhead."],
    algorithm: ["Trace an application call through framework, collective layer, transport layer, device, and network.", "Compare progress and completion models."],
    implementation: ["Build the same allreduce with sockets, MPI, Gloo, and accelerator backends.", "Inspect library-selected algorithms and overrides."],
    performance: ["CPU-centric and GPU-centric libraries optimize different bottlenecks.", "Transport choice changes eager thresholds, copies, and progress."],
    systems: ["MPI dominates HPC semantics; Gloo serves CPU collectives; UCX unifies transports; NCCL/RCCL/oneCCL/XCCL target accelerator ecosystems."],
    pitfalls: ["Treating APIs with similar names as identical semantics.", "Stacking layers without knowing who owns progress.", "Benchmarking different memory locations."],
    exercises: ex("Draw four software stacks.", "Port one benchmark across backends.", "Compare completion semantics.", "Find hidden host staging.", "Write a backend selection policy."),
  },
  {
    id: "nccl-topology", number: 26, module: "libraries", title: "NCCL Topology Discovery & Graphs", level: "Production", duration: "95 min",
    thesis: "NCCL converts discovered GPUs, NICs, CPUs, PCIe switches, and NVLink paths into communication graphs used to construct channels.",
    intuition: "Before routing trucks, the planner inventories roads, bridges, tolls, capacities, and which warehouses can access which loading docks.",
    math: ["Topology is a weighted graph of nodes and paths.", "Graph construction seeks high bandwidth, low path cost, and balanced resource reuse.", "Channel count trades parallel capacity against overhead."],
    algorithm: ["Discover local hardware.", "Classify path types and bandwidth.", "Search ring/tree graph patterns.", "Exchange inter-node topology information."],
    implementation: ["Read topology dumps and debug output.", "Relate logical ranks to PCI/NVLink/NIC paths.", "Understand transport choice per peer."],
    performance: ["Bad affinity or hidden topology changes graph quality.", "More channels improve utilization until launch/synchronization pressure dominates.", "Cross-NIC choices depend on locality and policy."],
    systems: ["NCCL graph construction underlies ring/tree selection and channel wiring."],
    pitfalls: ["Assuming rank order is the ring.", "Editing topology overrides without validation.", "Ignoring container visibility and virtualized devices."],
    exercises: ex("Annotate a topology dump.", "Score candidate rings.", "Choose NIC-local ranks.", "Diagnose a missing NVLink edge.", "Design graph search objectives."),
  },
  {
    id: "nccl-protocols", number: 27, module: "libraries", title: "NCCL Channels, Chunks, LL, LL128 & Simple", level: "Production", duration: "105 min",
    thesis: "NCCL protocols trade synchronization granularity, payload efficiency, latency, and bandwidth; channels and slicing create parallel pipelines.",
    intuition: "Simple ships full crates efficiently; low-latency protocols use smaller sealed parcels that can be forwarded sooner but carry more packaging.",
    math: ["Protocol efficiency=payload bytes/transported bytes.", "Total time depends on slice startup, number of channels, and per-channel bandwidth.", "Optimal chunk size changes with message and topology."],
    algorithm: ["Split tensor across channels.", "Split chunks into slices.", "Use protocol-specific readiness and forwarding.", "Select protocol/algorithm by estimated cost."],
    implementation: ["Explain Simple bulk buffers, LL flag/data packing, and LL128 line structure conceptually.", "Track per-step head/tail readiness."],
    performance: ["LL targets latency; Simple targets bulk bandwidth; LL128 balances low latency and efficiency on suitable paths.", "Excess channels consume GPU and protocol resources."],
    systems: ["NCCL selects algorithm and protocol jointly using topology and message size."],
    pitfalls: ["Interpreting protocol names as universal size rules.", "Ignoring payload overhead.", "Forcing a protocol across unsupported or poor paths."],
    exercises: ex("Calculate 50% payload efficiency.", "Model slice pipelining.", "Plot protocol crossovers.", "Find a readiness wraparound bug.", "Design a protocol selector."),
  },
  {
    id: "nccl-runtime", number: 28, module: "libraries", title: "NCCL Kernels, Proxies, Transports & Launch", level: "Production", duration: "110 min",
    thesis: "A production collective coordinates GPU kernels with CPU proxy progress and transport-specific operations while preserving CUDA stream semantics.",
    intuition: "The GPU assembly line handles local movement and reduction; a dispatcher arranges transfers that require NIC or operating-system participation.",
    math: ["End-to-end time=max(overlapped GPU work, proxy/transport progress)+dependencies.", "Batching launch work amortizes setup.", "Persistent work reduces repeated launch cost but occupies resources."],
    algorithm: ["Enqueue collective plan.", "Launch or join device kernel.", "Proxy posts and progresses transport operations.", "GPU and proxy exchange readiness through protocol buffers."],
    implementation: ["Trace bootstrap, communicator init, group launch, work descriptors, primitives, proxy operations, and completion.", "Study transport plugins and registered buffers."],
    performance: ["Proxy CPU placement and scheduling matter.", "Group launch reduces overhead.", "CUDA Graph capture requires stable, capture-safe behavior."],
    systems: ["NCCL integrates with framework streams, graph capture, communicator error handling, and plugins."],
    pitfalls: ["Blocking the proxy CPU.", "Destroying communicators with work in flight.", "Misreading enqueue completion as collective completion."],
    exercises: ex("Draw GPU/proxy lanes.", "Implement a progress-state machine.", "Model launch amortization.", "Diagnose a descheduled proxy.", "Design a capture-safe collective plan."),
  },
  {
    id: "programmable-collectives", number: 29, module: "libraries", title: "MSCCL, NVSHMEM & DeepEP", level: "Production", duration: "90 min",
    thesis: "Programmable schedules, one-sided GPU communication, and MoE-specialized runtimes expose optimization opportunities beyond fixed collective implementations.",
    intuition: "A standard carrier offers fixed services; programmable logistics lets experts script routes, while one-sided access lets authorized workers directly stock remote shelves.",
    math: ["Schedule makes dependencies and buffer lifetimes explicit.", "One-sided operations shift synchronization responsibility.", "MoE dispatch cost combines permutation, transfer, and combine."],
    algorithm: ["Express chunk dependencies as a schedule.", "Use put/get plus signals for one-sided exchange.", "Specialize sparse expert dispatch and combine."],
    implementation: ["Introduce MSCCL schedules, NVSHMEM symmetric heaps and signals, and DeepEP-style dispatch paths.", "Validate deadlock freedom and bounds."],
    performance: ["Specialization can exploit topology and workload regularity.", "Fine-grained operations risk overhead.", "Low-latency decode and high-throughput prefill need different paths."],
    systems: ["These systems complement general collectives for topology-specific or sparse communication."],
    pitfalls: ["Assuming one-sided means synchronization-free.", "Hard-coding one topology.", "Ignoring permutation memory bandwidth."],
    exercises: ex("Write a dependency schedule.", "Model put+signal.", "Separate dispatch from combine.", "Find a missing signal.", "Design prefill/decode MoE paths."),
  },
  {
    id: "data-parallel", number: 30, module: "training", title: "Data Parallelism", level: "Intermediate", duration: "80 min",
    thesis: "Data parallelism replicates model state, partitions examples, and globally combines gradients so every replica applies the same update.",
    intuition: "Four analysts use different survey samples, then average their measurements before each updates an identical report.",
    math: ["Global gradient for equal local batch sizes: g=(1/P)Σgᵣ.", "Communication volume is proportional to parameter gradient size, not batch size.", "Scaling efficiency=T₁/(P·Tₚ)."],
    algorithm: ["Forward and backward locally.", "Launch gradient allreduce as buckets become ready.", "Apply optimizer after required reductions complete."],
    implementation: ["PyTorch DDP gradient hooks and buckets.", "Overlap backprop with allreduce.", "Handle unused parameters and gradient accumulation."],
    performance: ["Bucket size balances overlap and launch count.", "Last bucket creates exposed tail.", "Slow workers delay synchronous progress."],
    systems: ["DDP, Horovod-style training, and replicated JAX meshes use this pattern."],
    pitfalls: ["Allreducing after the full backward pass unnecessarily.", "Incorrect loss scaling.", "Different parameter order across ranks."],
    exercises: ex("Compute global batch size.", "Draw backward/allreduce overlap.", "Tune bucket size.", "Diagnose double averaging.", "Design accumulation over four microbatches."),
  },
  {
    id: "zero-fsdp", number: 31, module: "training", title: "ZeRO Stages & FSDP", level: "Advanced", duration: "100 min",
    thesis: "ZeRO and FSDP trade communication and scheduling complexity for sharded optimizer state, gradients, and parameters.",
    intuition: "Instead of every office storing the full archive, each owns a section and temporarily retrieves missing pages only when needed.",
    math: ["Stage 1 shards optimizer state; Stage 2 adds gradient sharding; Stage 3 shards parameters.", "Per-rank model-state memory approaches 1/P for fully sharded components.", "Parameter allgather and gradient reduce-scatter replace replicated residency."],
    algorithm: ["Allgather a parameter unit before computation.", "Run forward/backward.", "Reduce-scatter gradients to owners.", "Update local shards and reshard."],
    implementation: ["Wrap modules into sharding units.", "Prefetch upcoming units.", "Free or retain gathered parameters based on reuse.", "Manage mixed precision and checkpointing."],
    performance: ["Unit size trades peak memory, overlap, and launch count.", "Forward and backward prefetch determine exposed communication.", "Host offload changes PCIe pressure."],
    systems: ["DeepSpeed ZeRO and PyTorch FSDP implement related sharded-state strategies."],
    pitfalls: ["Gathering the entire model at once.", "Checkpoint formats tied to one world size.", "Unexpected parameter materialization."],
    exercises: ex("Tabulate memory by ZeRO stage.", "Trace one layer.", "Model prefetch distance.", "Diagnose an allgather memory spike.", "Design elastic sharded checkpoints."),
  },
  {
    id: "tensor-sequence", number: 32, module: "training", title: "Tensor & Sequence Parallelism", level: "Advanced", duration: "105 min",
    thesis: "Tensor parallelism shards matrix dimensions and uses collectives to reconcile partial activations; sequence parallelism changes activation ownership to reduce replication.",
    intuition: "Several workshops build different slices of one large component, then either sum compatible partials or assemble distinct slices.",
    math: ["Column-parallel linear partitions output features; row-parallel linear produces partial sums requiring reduction.", "Communication scales with activation dimensions and sequence length.", "Sequence sharding converts replicated activations into per-rank segments."],
    algorithm: ["Column-parallel GEMM then optional gather.", "Row-parallel GEMM then allreduce/reduce-scatter.", "Sequence-parallel transitions via allgather and reduce-scatter."],
    implementation: ["Trace tensor shapes through MLP and attention blocks.", "Fuse communication with epilogues where possible.", "Use process meshes for DP×TP groups."],
    performance: ["Small GEMMs lose efficiency at high TP.", "Latency is paid every layer.", "Overlap opportunities are constrained by layer dependencies."],
    systems: ["Megatron-LM and inference engines use tensor-parallel collectives throughout transformer layers."],
    pitfalls: ["Choosing a collective without tracking tensor layout.", "Scaling TP beyond useful GEMM size.", "Confusing model and sequence axes."],
    exercises: ex("Shard a 4×8 matrix.", "Trace row-parallel output.", "Calculate activation bytes.", "Find a layout mismatch.", "Design TP degree per node."),
  },
  {
    id: "pipeline-context", number: 33, module: "training", title: "Pipeline & Context Parallelism", level: "Advanced", duration: "95 min",
    thesis: "Pipeline parallelism transfers activations between stage neighbors; context parallelism distributes long sequences and coordinates attention information.",
    intuition: "A factory line sends partially assembled products forward; context parallelism splits a very long document among readers who must exchange enough information to compute global attention.",
    math: ["Pipeline bubble fraction depends on stages and microbatches.", "Activation bytes depend on microbatch×sequence×hidden size.", "Attention communication may exchange K/V blocks or partial statistics."],
    algorithm: ["GPipe and 1F1B schedules.", "Send/receive activations and gradients.", "Ring attention or blockwise context exchange.", "Compose PP×CP×TP groups."],
    implementation: ["Tag microbatches and direction.", "Use separate streams carefully.", "Preserve causal and numerical softmax state across context shards."],
    performance: ["More microbatches shrink bubbles but increase overhead and activation state.", "Stage imbalance dominates pipeline utilization.", "Long-context communication competes with attention compute."],
    systems: ["Megatron-style pipeline/context parallelism and long-context training use these patterns."],
    pitfalls: ["Deadlock from inconsistent send/receive order.", "Too few microbatches.", "Incorrect causal ownership."],
    exercises: ex("Draw a four-stage schedule.", "Calculate bubble fraction.", "Trace ring attention.", "Find a microbatch tag collision.", "Balance uneven transformer stages."),
  },
  {
    id: "expert-parallel", number: 34, module: "training", title: "Expert Parallelism & MoE", level: "Advanced", duration: "105 min",
    thesis: "MoE converts routing decisions into irregular all-to-all traffic, with token permutation and load imbalance often as important as raw network bandwidth.",
    intuition: "A dispatcher sends each package to a specialized workshop, then returns the processed package to its original order.",
    math: ["Router selects top-k experts per token.", "Capacity factor bounds tokens accepted per expert.", "Communication bytes≈tokens×k×hidden width×element size, subject to locality."],
    algorithm: ["Score and select experts.", "Count and prefix-sum destinations.", "Pack/dispatch with alltoallv.", "Compute experts, combine, and unpermute."],
    implementation: ["Separate metadata and payload exchange.", "Use grouped GEMMs.", "Exploit node-local expert placement and specialized dispatch runtimes."],
    performance: ["Hot experts create stragglers.", "Permutation is memory-bandwidth intensive.", "Decode has tiny, latency-sensitive token counts; prefill favors throughput."],
    systems: ["DeepSpeed-MoE, Megatron expert parallelism, DeepEP, and large sparse models use these mechanisms."],
    pitfalls: ["Assuming equal token counts.", "Dropping tokens silently.", "Optimizing transfer while ignoring packing."],
    exercises: ex("Route eight tokens to four experts.", "Build count exchange.", "Simulate skewed routing.", "Find an unpermute error.", "Co-design expert placement and routing."),
  },
  {
    id: "frameworks", number: 35, module: "training", title: "Framework Integration: Torch, JAX & XLA", level: "Production", duration: "90 min",
    thesis: "Frameworks derive collective groups and schedules from program graphs, sharding specifications, autograd, and compiler transformations.",
    intuition: "The framework is a compiler-assisted stage manager: it knows tensor roles and can place communication where dependencies permit.",
    math: ["A device mesh names logical axes.", "A sharding spec maps tensor dimensions to mesh axes.", "Resharding induces collectives such as allgather, reduce-scatter, or all-to-all."],
    algorithm: ["Infer or specify tensor layouts.", "Lower layout transitions into collectives.", "Schedule with compute and reuse compiled graphs."],
    implementation: ["Contrast eager PyTorch process groups with compiled XLA/JAX sharding.", "Inspect graphs and collective groups.", "Use custom communication hooks cautiously."],
    performance: ["Compiler fusion can eliminate layout transitions.", "Dynamic shapes and recompilation affect serving/training.", "Group construction must match physical topology."],
    systems: ["Torch Distributed, DTensor, XLA SPMD, JAX pjit/shard_map, DeepSpeed, and Megatron occupy different layers."],
    pitfalls: ["Assuming logical mesh order is topology optimal.", "Hidden resharding.", "Graph breaks around communication."],
    exercises: ex("Map a 2×4 device mesh.", "Infer a reshard collective.", "Inspect a lowered graph.", "Find duplicate resharding.", "Design a topology-aware mesh mapper."),
  },
  {
    id: "tp-inference", number: 36, module: "inference", title: "Tensor & Pipeline Parallel Inference", level: "Advanced", duration: "95 min",
    thesis: "Inference repeats latency-sensitive collectives at every generated token; optimal parallelism balances model fit, GEMM efficiency, and interconnect cost.",
    intuition: "Training communicates for large batches; decoding repeatedly asks a small committee to agree before producing each next word.",
    math: ["Decode collective frequency scales with layers×tokens.", "Time per token≈compute+exposed communication+scheduling.", "Increasing TP reduces per-rank GEMM size while increasing participants."],
    algorithm: ["Shard attention and MLP projections.", "Reduce partial outputs per layer.", "Pipeline requests or microbatches across stages."],
    implementation: ["Use persistent KV ownership and stable groups.", "Capture repeated decode graphs.", "Separate prefill and decode execution profiles."],
    performance: ["Inter-token dependency exposes latency.", "Small decode batches underutilize GPUs.", "Pipeline parallelism adds stage latency and bubbles."],
    systems: ["TensorRT-LLM, vLLM, SGLang, and Megatron-derived engines use TP/PP combinations."],
    pitfalls: ["Selecting TP only to fit memory.", "Benchmarking throughput without tail latency.", "Using prefill tuning for decode."],
    exercises: ex("Count collectives per token.", "Trace one TP layer.", "Model TP degree crossover.", "Diagnose rising inter-token latency.", "Choose TP/PP for two eight-GPU nodes."),
  },
  {
    id: "serving-scheduling", number: 37, module: "inference", title: "Prefill, Decode & Continuous Batching", level: "Advanced", duration: "90 min",
    thesis: "Serving schedulers shape communication by mixing long compute-heavy prefill work with short latency-sensitive decode work.",
    intuition: "Prefill is loading an entire shipment; decode is delivering one urgent parcel at a time. Combining them improves utilization but can delay urgent work.",
    math: ["Throughput=tokens/time; latency includes queue, prefill, and inter-token gaps.", "Batch composition changes GEMM and collective sizes every iteration.", "Tail latency depends on scheduling and longest active sequence."],
    algorithm: ["Admit requests.", "Allocate KV blocks.", "Form continuous batches.", "Schedule prefill chunks and decode steps.", "Retire completed sequences."],
    implementation: ["Track variable sequence lengths and block tables.", "Coordinate identical batch metadata across TP ranks.", "Use chunked prefill and priority policies."],
    performance: ["Larger batches improve throughput but increase queueing.", "Prefill can block decode communication.", "Frequent metadata synchronization adds latency."],
    systems: ["Paged attention and continuous batching are central to vLLM/SGLang-style serving."],
    pitfalls: ["Reporting only average latency.", "Divergent scheduler state across ranks.", "Starving long prompts or decode requests."],
    exercises: ex("Build a two-request timeline.", "Implement a toy continuous scheduler.", "Plot throughput/latency tradeoff.", "Find a rank-divergent batch.", "Design prefill/decode isolation."),
  },
  {
    id: "kv-disaggregation", number: 38, module: "inference", title: "KV Cache Transfer & Disaggregated Inference", level: "Production", duration: "100 min",
    thesis: "Disaggregation separates prefill and decode resources but turns KV-cache placement and transfer into a first-class distributed systems problem.",
    intuition: "One facility processes raw documents, then ships a large indexed archive to another facility that answers rapid follow-up questions.",
    math: ["KV bytes scale with layers×tokens×KV heads×head dimension×2×element size.", "Transfer must often fit beneath prefill completion or decode admission latency.", "Replicating KV trades network cost for memory."],
    algorithm: ["Select prefill and decode workers.", "Allocate destination KV blocks.", "Stream or bulk-transfer cache.", "Publish readiness and route request continuation."],
    implementation: ["Use RDMA/GPU transfer paths.", "Encode layer and block layout.", "Handle retries, ownership, and lifecycle without stale cache."],
    performance: ["KV movement can dominate short generation.", "Topology-aware placement reduces transfer.", "Chunked transfer can overlap later prefill layers."],
    systems: ["Modern serving clusters explore disaggregated prefill/decode and remote KV-cache tiers."],
    pitfalls: ["Counting only payload, not metadata and synchronization.", "Starting decode before cache visibility.", "Leaking or reusing blocks across requests."],
    exercises: ex("Calculate KV bytes.", "Draw transfer overlap.", "Choose bulk versus streaming.", "Diagnose stale readiness.", "Design fault-tolerant KV ownership."),
  },
  {
    id: "speculative-moe-serving", number: 39, module: "inference", title: "Speculative Decoding & MoE Serving", level: "Production", duration: "95 min",
    thesis: "Speculation changes communication granularity through verification batches, while MoE serving adds dynamic expert traffic whose decode regime is extremely latency sensitive.",
    intuition: "A junior writer drafts several words; a senior reviewer accepts a run at once. Sparse experts are specialists consulted only for relevant tokens.",
    math: ["Effective speedup depends on draft cost, acceptance length, and verification cost.", "Verification turns several token positions into a larger batch.", "MoE decode messages are small but numerous and imbalanced."],
    algorithm: ["Draft k candidates.", "Transfer/verify candidates.", "Accept prefix and resample.", "Route verification tokens through experts."],
    implementation: ["Coordinate draft and target model state.", "Batch verification across requests.", "Use low-latency expert dispatch paths."],
    performance: ["Low acceptance wastes compute and communication.", "Verification may improve collective efficiency by increasing tensor size.", "Expert locality and batching shape tail latency."],
    systems: ["Serving engines combine speculative methods, TP collectives, and sparse expert routing."],
    pitfalls: ["Ignoring synchronization after rejection.", "Assuming throughput gain implies latency gain.", "Using throughput MoE kernels for single-token decode."],
    exercises: ex("Compute accepted tokens per cycle.", "Simulate acceptance.", "Model verification batching.", "Find a rejected-prefix state bug.", "Co-design speculative and expert placement."),
  },
  {
    id: "failures", number: 40, module: "operations", title: "Deadlocks, Livelocks & Timeouts", level: "Production", duration: "95 min",
    thesis: "Most collective hangs come from violated distributed ordering, missing progress, resource cycles, or a failed participant—not from mysterious library behavior.",
    intuition: "Four people each wait for a package held by the next person; every person is locally reasonable, but the global dependency graph contains a cycle.",
    math: ["Deadlock requires mutual exclusion, hold-and-wait, no preemption, and circular wait.", "Timeout is a detector, not a root cause.", "A wait-for graph exposes dependency cycles."],
    algorithm: ["Record last entered/completed collective per rank.", "Align sequence numbers and tensor metadata.", "Inspect transport/proxy progress.", "Separate slow progress from no progress."],
    implementation: ["Add watchdogs and asynchronous error checks.", "Capture rank-local traces.", "Abort communicators consistently after fatal failure."],
    performance: ["Aggressive timeouts create false positives under congestion.", "Livelock consumes resources without completion.", "Recovery cost depends on checkpoint and membership model."],
    systems: ["NCCL watchdogs, framework process groups, MPI failure behavior, and job schedulers interact."],
    pitfalls: ["Increasing timeout before finding the mismatch.", "Collecting logs from only one rank.", "Continuing with corrupted communicator state."],
    exercises: ex("Draw a two-rank deadlock.", "Build a sequence-number checker.", "Differentiate slow versus stuck.", "Diagnose mismatched collectives.", "Design coordinated abort and restart."),
  },
  {
    id: "stragglers", number: 41, module: "operations", title: "Stragglers & Topology Imbalance", level: "Production", duration: "85 min",
    thesis: "Collective latency exposes the slowest arrival, slowest path, or most overloaded resource; averages conceal the responsible tail.",
    intuition: "A relay team finishes when its slowest required handoff finishes, even if most runners are fast.",
    math: ["Collective start skew=max arrival−min arrival.", "Observed duration for an early rank includes wait for later dependencies.", "Tail metrics and per-rank variance identify imbalance."],
    algorithm: ["Align timelines by collective sequence.", "Separate arrival, active transfer, and completion phases.", "Correlate outliers with topology and hardware counters."],
    implementation: ["Instrument per-rank timestamps and CUDA events.", "Collect CPU scheduling, GPU, NIC, and switch signals.", "Run pairwise isolation tests."],
    performance: ["Thermal throttling, noisy neighbors, routing collisions, and bad affinity create tails.", "One degraded link affects repeated logical edges."],
    systems: ["Training iteration time follows slowest synchronous participant; serving tail latency follows the worst shard dependency."],
    pitfalls: ["Calling every long collective a network problem.", "Comparing unsynchronized host clocks blindly.", "Removing outliers from the report."],
    exercises: ex("Calculate start skew.", "Plot per-rank timelines.", "Localize one bad edge.", "Diagnose CPU descheduling.", "Design straggler-resilient scheduling."),
  },
  {
    id: "debugging", number: 42, module: "operations", title: "NCCL, MPI & UCX Debugging", level: "Production", duration: "105 min",
    thesis: "Effective debugging moves layer by layer: application semantics, framework scheduling, collective plan, transport progress, device state, and physical fabric.",
    intuition: "Follow a missing package from the order system to the warehouse, truck, road, destination dock, and final shelf—without skipping layers.",
    math: ["Use sequence correlation rather than wall-clock proximity alone.", "Counter deltas must be normalized by interval and expected traffic.", "A/B tests isolate one variable at a time."],
    algorithm: ["Reproduce minimally.", "Capture versions/topology/environment.", "Enable targeted logs.", "Align rank traces.", "Validate links independently.", "Bisect configuration."],
    implementation: ["Use NCCL debug subsystems, topology dumps, async error handling, MPI traces, UCX logging, and framework distributed debug modes."],
    performance: ["Verbose logging perturbs timing.", "Debug builds and forced algorithms change behavior.", "Repeated counters distinguish transient from persistent faults."],
    systems: ["nsys, perf, flamegraphs, ib tools, ethtool, packet captures, and switch telemetry cover different layers."],
    pitfalls: ["Turning on every log at once.", "Changing multiple environment variables.", "Publishing secrets or addresses from logs."],
    exercises: ex("Create a capture checklist.", "Align four rank logs.", "Bisect ring versus tree.", "Find the first divergent sequence.", "Design a portable debug bundle."),
  },
  {
    id: "profiling", number: 43, module: "operations", title: "Profiling & Performance Counters", level: "Production", duration: "100 min",
    thesis: "A useful profile connects application phases to GPU kernels, memory traffic, transport activity, NIC counters, and switch queues on one causal timeline.",
    intuition: "A factory dashboard must show when orders arrived, machines worked, conveyors stalled, and loading docks backed up—not just total daily output.",
    math: ["Overlap ratio=overlapped communication time/communication time.", "Exposed communication lies on the iteration critical path.", "Counter rate=delta counter/delta time."],
    algorithm: ["Mark framework ranges.", "Capture GPU and CPU timelines.", "Correlate collective IDs.", "Sample NIC/switch counters.", "Compare expected versus observed bytes."],
    implementation: ["Use Nsight Systems, framework profilers, CUPTI ranges, perf, flamegraphs, and network telemetry.", "Automate synchronized captures."],
    performance: ["Tracing overhead changes microsecond events.", "Sampling misses short bursts.", "Aggregate utilization can hide link-level hotspots."],
    systems: ["Production observability needs low-overhead continuous metrics plus high-detail triggered captures."],
    pitfalls: ["Equating kernel duration with exposed cost.", "Ignoring warm-up.", "Comparing counters with different reset semantics."],
    exercises: ex("Calculate overlap ratio.", "Annotate a training trace.", "Estimate expected NIC bytes.", "Diagnose a false idle gap.", "Design always-on collective telemetry."),
  },
  {
    id: "scale-simulator", number: 44, module: "operations", title: "Simulating 1,024 GPUs", level: "Production", duration: "110 min",
    thesis: "Discrete-event simulation lets us explore algorithms, mappings, failures, and congestion before expensive cluster experiments, provided the model is calibrated and explicit.",
    intuition: "A flight simulator is useful because it models the important physics and failure modes—not because it reproduces every molecule of air.",
    math: ["Events represent transfer start/completion, reduction, and resource release.", "Links are capacity-constrained queues.", "Calibration fits α, bandwidth, concurrency, and contention from measurements."],
    algorithm: ["Represent topology graph.", "Compile collective schedule into events.", "Reserve resources and advance virtual time.", "Collect critical paths and utilization."],
    implementation: ["Start with deterministic α–β links.", "Add chunking, shared resources, routing, jitter, and failures.", "Validate on small real systems."],
    performance: ["Simulation complexity grows with ranks×chunks×steps.", "Aggregate equivalent flows at scale.", "Sensitivity analysis matters more than one predicted number."],
    systems: ["Schedulers and communication researchers use simulation for topology and algorithm co-design."],
    pitfalls: ["Presenting uncalibrated output as prediction.", "Ignoring shared PCIe/NIC resources.", "Adding complexity without validation."],
    exercises: ex("Simulate four-rank ring.", "Add shared-link contention.", "Scale with flow aggregation.", "Find a causality bug.", "Compare 2D and hierarchical allreduce at 1,024 GPUs."),
  },
  {
    id: "mini-nccl", number: 45, module: "operations", title: "Build a Mini NCCL", level: "Production", duration: "Project",
    thesis: "Building a small collective runtime forces semantics, topology, protocol, progress, buffers, and failure handling into one coherent design.",
    intuition: "After studying engines, build a small one: not to match a production engine, but to discover why every subsystem exists.",
    math: ["Specify cost model and invariants before optimization.", "Prove buffer bounds and dependency acyclicity.", "Measure against theoretical link and memory ceilings."],
    algorithm: ["Bootstrap ranks.", "Discover a simplified topology.", "Construct ring/tree channels.", "Implement broadcast, allgather, reduce-scatter, and allreduce.", "Add selection."],
    implementation: ["Phase 1 TCP/CPU.", "Phase 2 shared memory.", "Phase 3 CUDA buffers and kernels.", "Phase 4 RDMA transport.", "Phase 5 channels, tracing, and failures."],
    performance: ["Benchmark latency curves, bandwidth plateaus, CPU overhead, memory traffic, and overlap.", "Compare with MPI/NCCL without expecting feature parity."],
    systems: ["The project mirrors the architectural boundaries found in production collective libraries."],
    pitfalls: ["Optimizing before proving correctness.", "No sequence IDs or buffer ownership model.", "Hiding transport errors."],
    exercises: ex("Write the semantic test suite.", "Implement one ring channel.", "Add tree selection.", "Inject a dropped participant.", "Document production gaps and next architecture."),
  },
  {
    id: "cluster-design", number: 46, module: "operations", title: "Think Like a Collective-System Designer", level: "Production", duration: "Capstone",
    thesis: "Expert design begins with workload tensor flows, derives communication requirements, maps them onto hierarchy, and validates the result with models and measurements.",
    intuition: "Do not start by buying the fastest road. Start with what must move, when it must arrive, where it begins, and which other traffic shares the route.",
    math: ["Derive bytes and frequency for each DP/TP/PP/CP/EP group.", "Build a resource-demand matrix by topology tier.", "Evaluate throughput, tail latency, failure domains, and cost together."],
    algorithm: ["Characterize workload.", "Choose parallel decomposition.", "Place groups physically.", "Select algorithms/protocols.", "Model contention.", "Prototype, measure, and iterate."],
    implementation: ["Produce topology diagrams, communication timelines, benchmark plans, observability, and rollback criteria.", "Document assumptions and version boundaries."],
    performance: ["Optimize exposed critical-path communication, not impressive isolated bandwidth.", "Preserve headroom for imbalance and failures.", "Revalidate as models and software change."],
    systems: ["This method applies to Llama/GPT dense models, DeepSeek-style MoE, training clusters, and distributed inference fleets."],
    pitfalls: ["Copying another cluster’s ratios.", "Optimizing one collective in isolation.", "Ignoring operability, upgrade paths, and failure recovery."],
    exercises: ex("Derive traffic for a toy transformer.", "Create a topology mapping.", "Model three failure scenarios.", "Review a misleading benchmark.", "Defend a 1,024-GPU training and serving architecture."),
  },
];

export const glossary = [
  ["α (alpha)", "Fixed startup latency paid by a communication step."],
  ["β (beta)", "Seconds per byte; approximately the inverse of effective bandwidth."],
  ["Rank", "A participant’s ordered identifier inside a communication group."],
  ["Communicator", "An ordered group plus the state required to coordinate collectives."],
  ["Channel", "An independent logical communication pipeline over part of a tensor."],
  ["Chunk", "A tensor partition assigned to a step or channel."],
  ["Slice", "A finer-grained protocol unit used to pipeline readiness."],
  ["Critical path", "The longest dependency chain that determines completion time."],
  ["GPUDirect RDMA", "A path allowing a capable NIC to DMA to or from GPU memory."],
  ["WQE", "A work queue element describing a transport operation to a NIC."],
  ["Doorbell", "A notification telling hardware that new queued work is available."],
  ["CQ", "A completion queue carrying completion records for submitted work."],
  ["QP", "An RDMA queue pair containing send/receive work queues and transport state."],
  ["Bisection bandwidth", "Capacity crossing a cut that divides a topology into two parts."],
  ["Incast", "Many senders simultaneously target a smaller receiver or set of links."],
  ["Allreduce", "Reduction whose complete result is delivered to every rank."],
  ["Reduce-scatter", "Reduction whose final result is partitioned across ranks."],
  ["Allgather", "Replication of all rank-owned shards to every rank."],
  ["All-to-all", "Personalized exchange in which every rank sends a distinct shard to every rank."],
  ["Straggler", "A participant or path whose late progress delays synchronized completion."],
];
